<!DOCTYPE html>
<html lang="uk">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> -->
</head>

<body>

    <div class="container">
        <div class="col-md-6">
            <div id="my-map"></div>
        </div>
    </div>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" />
    <style>
        html1,
        body1,
        #my-map {
            width: 100%;
            height: 100%;
            margin: 0;
            max-width: 700px;
        }
    </style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js"></script>


    <script>
        // The API Key provided is restricted to JSFiddle website
        // Get your own API Key on https://myprojects.geoapify.com
        // var myAPIKey = "b8e29e63c5ba427682d06de390d243b2";
        // Leaflet has native support for raster maps, So you can create a map with a few commands only!

        // The Leaflet map Object
        const map = L.map('my-map').setView([48.1500327, 11.5753989], 10);

        // The API Key provided is restricted to JSFiddle website
        // Get your own API Key on https://myprojects.geoapify.com
        const myAPIKey = "b8e29e63c5ba427682d06de390d243b2";

        // Retina displays require different mat tiles quality
        const isRetina = L.Browser.retina;

        const baseUrl = "https://maps.geoapify.com/v1/tile/osm-bright/{z}/{x}/{y}.png?apiKey={apiKey}";
        const retinaUrl = "https://maps.geoapify.com/v1/tile/osm-bright/{z}/{x}/{y}@2x.png?apiKey={apiKey}";

        // Add map tiles layer. Set 20 as the maximal zoom and provide map data attribution.
        L.tileLayer(isRetina ? retinaUrl : baseUrl, {
            attribution: 'Powered by <a href="https://www.geoapify.com/" target="_blank">Geoapify</a> | © OpenStreetMap <a href="https://www.openstreetmap.org/copyright" target="_blank">contributors</a>',
            apiKey: myAPIKey,
            maxZoom: 20,
            id: 'osm-bright',
        }).addTo(map);

        //add a marker with icon generated by Geoapify Marker Icon API
        const markerIcon = L.icon({
            iconUrl: `https://api.geoapify.com/v1/icon?size=xx-large&type=awesome&color=%233e9cfe&icon=paw&apiKey=${myAPIKey}`,
            iconSize: [31, 46], // size of the icon
            iconAnchor: [15.5, 42], // point of the icon which will correspond to marker's location
            popupAnchor: [0, -45] // point from which the popup should open relative to the iconAnchor
        });

        const zooMarkerPopup = L.popup().setContent("This is Munich Zoo");
        const zooMarker = L.marker([48.096980, 11.555466], {
            icon: markerIcon
        }).bindPopup(zooMarkerPopup).addTo(map);
    </script>





    <div class="container">
        <form method="GET">
            <p>
                <input type="text" name="address" placeholder="Enter address">
            </p>

            <input type="submit" name="submit_address">
        </form>
        <br>
        <form method="GET">
            <p>
                <input type="text" name="latitude" placeholder="Enter latitude">
            </p>
            <p>
                <input type="text" name="longitude" placeholder="Enter longitude">
            </p>
            <input type="submit" name="submit_coordinates">
        </form>

        @if(request()->has('address'))
        <iframe width="100%" height="500" src="https://maps.google.com/maps?q=<?php echo $address; ?>&output=embed"></iframe>
        @endif

        @if($latitude && $longitude)
        <iframe width="100%" height="500" src="https://maps.google.com/maps?q=<?php echo $latitude; ?>,<?php echo $longitude; ?>&output=embed"></iframe>
        @endif
    </div>
</body>

</html>
